steps:
  # install / setup ci
  - name: node:$_DEPLOYMENT_NODE_VERSION
    entrypoint: npm
    args: ['install']

  #
  # Generate the static site
  #
  - name: node:$_DEPLOYMENT_NODE_VERSION
    entrypoint: npm
    args: ['--openssl-legacy-provider', 'run', 'build']

  #
  # Deploy to firebase channel, using the PR #
  # store log to /workspace to get the channel URL
  #
  - name: gcr.io/$_DEPLOYMENT_PROJECT/firebase
    entrypoint: bash
    args: ['-c', 'firebase deploy --project=$_DEPLOYMENT_PROJECT --config=firebase-$_DEPLOYMENT_ENVIRONMENT.json --only hosting:$_DEPLOYMENT_HOST_NAME']

substitutions:
    _DEPLOYMENT_ENVIRONMENT: '${_DEPLOYMENT_ENVIRONMENT}'
    _DEPLOYMENT_PROJECT: '${_DEPLOYMENT_PROJECT}'
    _DEPLOYMENT_NODE_VERSION: '${_DEPLOYMENT_NODE_VERSION}'
    _DEPLOYMENT_HOST_NAME: '${_DEPLOYMENT_HOST_NAME}'


options:
  logging: CLOUD_LOGGING_ONLY
