codecov:
  require_ci_to_pass: true
  branch: main
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true
