/** Enum used internally to query allowable actions via mixin. */
export enum AllowableActions {
  ADDRESS_CHANGE = 1, // skip 0 which is falsy
  AGM_EXTENSION,
  AGM_LOCATION_CHANGE,
  AMALGAMATION,
  AMALGAMATION_OUT,
  ANNUAL_REPORT,
  CONSENT_AMALGAMATION_OUT,
  CONSENT_CONTINUATION_OUT,
  CONTINUATION_OUT,
  COURT_ORDER,
  DETAIL_COMMENT,
  DIGITAL_CREDENTIALS,
  DIRECTOR_CHANGE
}
