export enum AllowableActions {
  ADDRESS_CHANGE = 'addressChange',
  ADMINISTRATIVE_DISSOLUTION = 'administrativeDissolution',
  ANNUAL_REPORT = 'annualReport',
  BUSINESS_INFORMATION = 'businessInformation',
  BUSINESS_SUMMARY = 'businessSummary',
  CONSENT_CONTINUATION_OUT = 'consentContinuationOut',
  CORRECTION = 'correction',
  COURT_ORDER = 'courtOrder',
  DETAIL_COMMENT = 'detailComment',
  DIGITAL_CREDENTIALS = 'digitalCredentials',
  DIRECTOR_CHANGE = 'directorChange',
  FREEZE_UNFREEZE = 'freezeUnfreeze',
  LIMITED_RESTO_CONVERT = 'limitedRestoConvert',
  LIMITED_RESTO_EXTEND = 'limitedRestoExtend',
  PUT_BACK_ON = 'putBackOn',
  RECORD_CONVERSION = 'recordConversion',
  REGISTRARS_NOTATION = 'registrarsNotation',
  REGISTRARS_ORDER = 'registrarsOrder',
  RESTORATION = 'restoration',
  STAFF_COMMENT = 'staffComment',
  TRANSITION = 'transition',
  VOLUNTARY_DISSOLUTION = 'voluntaryDissolution',
}
