/** List of actions authorized via roles. See Authorizations module. */

export enum AuthorizedActions {
    ADDRESS_CHANGE_FILING,
    ADMIN_DISSOLUTION_FILING,
    AGM_CHG_LOCATION_FILING,
    AGM_EXTENSION_FILING,
    AMALGAMATION_FILING,
    ANNUAL_REPORT_FILING,
    BLANK_CERTIFY_STATE,
    CONSENT_AMALGAMATION_OUT_FILING,
    CONSENT_CONTINUATION_OUT_FILING,
    COURT_ORDER_FILING,
    COURT_ORDER_POA,
    DIGITAL_CREDENTIALS,
    DIRECTOR_CHANGE_FILING,
    EDITABLE_CERTIFY_NAME,
    EDITABLE_COMPLETING_PARTY,
    FILE_AND_PAY,
    INCORPORATION_APPLICATION_FILING, // Coops and Corps
    NO_COMPLETING_PARTY_MESSAGE_BOX,
    NO_CONTACT_INFO,
    NOTICE_WITHDRAWAL_FILING,
    OVERRIDE_NIGS,
    SAVE_DRAFT,
    SBC_BREADCRUMBS,
    STAFF_BREADCRUMBS,
    STAFF_FILINGS,
    STAFF_PAYMENT,
    THIRD_PARTY_CERTIFY_STMT
  }
