/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActions {
    ADMIN_DISSOLUTION_FILING,
    ALTERATION_FILING,
    AMALGAMATION_FILING,
    AMALGAMATION_OUT_FILING,
    AML_OVERRIDES,
    BLANK_CERTIFY_STATE,
    BLANK_COMPLETING_PARTY,
    CONTINUATION_IN_FILING,
    CONTINUATION_OUT_FILING,
    COOP_CORRECTION_FILING,
    CORP_CORRECTION_FILING,
    COURT_ORDER_FILING,
    COURT_ORDER_POA,
    EDITABLE_CERTIFY_NAME,
    EDITABLE_COMPLETING_PARTY,
    FILE_AND_PAY,
    FIRM_ADD_BUSINESS,
    FIRM_CONVERSION_FILING,
    FIRM_DISSOLUTION_FILING, // firm voluntaty dissolution
    FIRM_EDITABLE_COMPLETING_PARTY,
    FIRM_EDITABLE_EMAIL_ADDRESS,
    FIRM_NO_MIN_START_DATE,
    INCORPORATION_APPLICATION_FILING, // Coops and Corps
    NO_COMPLETING_PARTY_MESSAGE_BOX,
    NO_CONTACT_INFO,
    NOTICE_WITHDRAWAL_FILING,
    OTHER_DISSOLUTION_FILING, // non-firm voluntary dissolution
    OVERRIDE_NIGS,
    REGISTRATION_FILING,
    RESTORATION_FILING,
    SAVE_DRAFT,
    SBC_BREADCRUMBS,
    STAFF_BREADCRUMBS,
    STAFF_COMMENTS,
    STAFF_PAYMENT,
    THIRD_PARTY_CERTIFY_STMT
  }
