/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActions {
    ADMIN_DISSOLUTION_FILING,
    AMALGAMATION_OUT_FILING,
    BLANK_CERTIFY_STATE,
    CONTINUATION_OUT_FILING,
    COURT_ORDER_FILING,
    COURT_ORDER_POA,
    DETAIL_COMMENTS,
    EDITABLE_CERTIFY_NAME,
    EDITABLE_COMPLETING_PARTY,
    FILE_AND_PAY,
    INCORPORATION_APPLICATION_FILING, // Coops and Corps
    NO_COMPLETING_PARTY_MESSAGE_BOX,
    NO_CONTACT_INFO,
    NOTICE_WITHDRAWAL_FILING,
    OVERRIDE_NIGS,
    SBC_BREADCRUMBS,
    STAFF_BREADCRUMBS,
    STAFF_COMMENTS,
    STAFF_PAYMENT,
    THIRD_PARTY_CERTIFY_STMT
  }
