/** Statuses used before business exists. */
export enum EntityStatus {
  DRAFT_AMALGAMATION = 'DRAFT_AMALGAMATION',
  DRAFT_CONTINUATION_IN = 'DRAFT_CONTINUATION_IN',
  DRAFT_INCORP_APP = 'DRAFT_INCORP_APP',
  DRAFT_REGISTRATION = 'DRAFT_REGISTRATION',
  FILED_AMALGAMATION = 'FILED_AMALGAMATION',
  FILED_CONTINUATION_IN = 'FILED_CONTINUATION_IN',
  FILED_INCORP_APP = 'FILED_INCORP_APP',
  FILED_REGISTRATION = 'FILED_REGISTRATION',
}
