export enum FilingStatus {
  APPROVED = 'APPROVED',
  AWAITING_REVIEW = 'AWAITING_REVIEW',
  CANCELLED = 'CANCELLED',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  COMPLETED = 'COMPLETED',
  CORRECTED = 'CORRECTED',
  DELETED = 'DELETED',
  DRAFT = 'DRAFT',
  EPOCH = 'EPOCH', // legacy, not used by UI
  ERROR = 'ERROR',
  NEW = 'NEW', // used for Todo List items only (ie, not yet a filing)
  PAID = 'PAID',
  PENDING = 'PENDING',
  PENDING_CORRECTION = 'PENDING_CORRECTION',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}
