export enum FilingStatus {
  COMPLETED = 'COMPLETED',
  DRAFT = 'DRAFT',
  EPOCH = 'EPOCH',
  ERROR = 'ERROR',
  NEW = 'NEW',
  PAID = 'PAID',
  PENDING = 'PENDING',
  PENDING_CORRECTION = 'PENDING_CORRECTION',
}
